//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gameoflife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGame
    {
        public int UserGameID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
        public string Cells { get; set; }
    
        public virtual User User { get; set; }
    }
}
